export const productData =[
    {
        category: "Food",
        description: "It is made of real chicken and liver meat to give a dog healthy skin and shinier furr.",
        discount: 15,
        inventory: 10,
        plusPoints: 100,
        price: 50,
        productId: "PET01001",
        productImages: "https://s3.ap-south-1.amazonaws.com/petswonder.productimages/PET01002.JPG",
        sellerNumber: 9959183841,
        species: "Dog",
        title: "Chicken and Liver in gravy",
    },
    {
        category: "Food",
        description: "JerHigh Chicken and Vegetable in Gravy is a high quality dog food suitable for all dog breeds and full of nutritional value, components of inulin and fiber to improve digestive system and excretory system.",
        discount: 15,
        inventory: 10,
        plusPoints: 100,
        price: 50,
        productId: "PET01002",
        productImages: "https://s3.ap-south-1.amazonaws.com/petswonder.productimages/PET01002.JPG",
        sellerNumber: 9959183841,
        species: "Dog",
        title: "Chicken and Vegetable in gravy ",
    },
    {
        category: "Food",
        description: "Fine Natural Meat Gravy for Dogs Healthy and Digestible reward.",
        discount: 15,
        inventory: 10,
        plusPoints: 100,
        price: 50,
        productId: "PET01003",
        productImages: "https://s3.ap-south-1.amazonaws.com/petswonder.productimages/PET01003.JPG",
        sellerNumber: 9959183841,
        species: "Dog",
        title: "Chicken and Grilled in gravy",
    },
    {
        category: "Food",
        description: "Fine Natural Meat Gravy for Dogs↵Healthy and Digestible reward.↵",
        discount: 15,
        inventory: 10,
        plusPoints: 100,
        price: 50,
        productId: "PET01004",
        productImages: "https://s3.ap-south-1.amazonaws.com/petswonder.productimages/PET01004.JPG",
        sellerNumber: 9959183841,
        species: "Dog",
        title: "Roasted Duck in gravy",
    },
    {
        category: "Food",
        description: "It is made of real chicken and liver meat to give a dog healthy skin and shinier furr.",
        discount: 15,
        inventory: 10,
        plusPoints: 100,
        price: 50,
        productId: "PET01001",
        productImages: "https://s3.ap-south-1.amazonaws.com/petswonder.productimages/PET01002.JPG",
        sellerNumber: 9959183841,
        species: "Dog",
        title: "Chicken and Liver in gravy",
    },
    {
        category: "Food",
        description: "JerHigh Chicken and Vegetable in Gravy is a high quality dog food suitable for all dog breeds and full of nutritional value, components of inulin and fiber to improve digestive system and excretory system.",
        discount: 15,
        inventory: 10,
        plusPoints: 100,
        price: 50,
        productId: "PET01002",
        productImages: "https://s3.ap-south-1.amazonaws.com/petswonder.productimages/PET01002.JPG",
        sellerNumber: 9959183841,
        species: "Dog",
        title: "Chicken and Vegetable in gravy ",
    },
    {
        category: "Food",
        description: "Fine Natural Meat Gravy for Dogs Healthy and Digestible reward.",
        discount: 15,
        inventory: 10,
        plusPoints: 100,
        price: 50,
        productId: "PET01003",
        productImages: "https://s3.ap-south-1.amazonaws.com/petswonder.productimages/PET01003.JPG",
        sellerNumber: 9959183841,
        species: "Dog",
        title: "Chicken and Grilled in gravy",
    },
    {
        category: "Food",
        description: "Fine Natural Meat Gravy for Dogs↵Healthy and Digestible reward.↵",
        discount: 15,
        inventory: 10,
        plusPoints: 100,
        price: 50,
        productId: "PET01004",
        productImages: "https://s3.ap-south-1.amazonaws.com/petswonder.productimages/PET01004.JPG",
        sellerNumber: 9959183841,
        species: "Dog",
        title: "Roasted Duck in gravy",
    }
];